source 'https://rubygems.org'

ruby "2.0.0"

gem 'redcarpet', '~> 2.3.0', :git => "https://github.com/byronsanchez/redcarpet-footnotes.git", :tag => "v2.3.0-footnotes"
gem 'pygments.rb', '~> 0.5.4'
gem 'yajl-ruby', '~> 1.1.0'
gem 'posix-spawn', '~> 0.3.6'
